Script started on 2017年03月20日 (週一) 10時25分13秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami;pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git con[K[K[K[K[K[K[Kgit config -l
user.email=keithchan907@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/keithchan907/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github.com/keithchan907/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m ^C
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月20日 (週一) 10時26分56秒
